### PR TITLE
Add postBodyJson

### PR DESCRIPTION
**Pull request by kochrt**
Given how common json data is in POST requests; would be nice to it available without having to parse it yourself.

Accompanies https://github.com/PerfectlySoft/Perfect-HTTPServer/pull/10

### CODE REVIEW

**Comment by mxcl** [comment]
This PR is over a year old with no comments or activity.

I am *considering* committing to Perfect as a solution for a system I am working on and this stale PR is worrying to me.

Can a maintainer chime in?

**Comment by kjessup** [comment]
Hello, sorry for the lack of feedback on this. We had added the following quite a while ago and, in my opinion, it took care of this need:

https://github.com/PerfectlySoft/Perfect-HTTP/blob/master/Sources/PerfectHTTP/TypedRoutes.swift#L89

It lets you decode the body in a more type-safe manner. I'm open-ish to adding what this PR proposes, but it seems a little redundant given the above. Thoughts?

**Comment by mxcl** [comment]
Thanks for the response, I wanted to gauge the pulse of the project. I agree this PR is no longer needed. Close it?

**Comment by kochrt** [comment]
I'm ok with that.

**Pull request closed without merging**
